# Distribution Statement A. Approved for public release, distribution is unlimited.
# ---
# THIS SOURCE CODE IS UNDER THE CUSTODY AND ADMINISTRATION OF THE GOVERNMENT OF THE UNITED STATES OF AMERICA.
# BY USING, MODIFYING, OR DISSEMINATING THIS SOURCE CODE, YOU ACCEPT THE TERMS AND CONDITIONS IN THE NRL OPEN LICENSE AGREEMENT.
# USE, MODIFICATION, AND DISSEMINATION ARE PERMITTED ONLY IN ACCORDANCE WITH THE TERMS AND CONDITIONS OF THE NRL OPEN LICENSE AGREEMENT.
# NO OTHER RIGHTS OR LICENSES ARE GRANTED. UNAUTHORIZED USE, SALE, CONVEYANCE, DISPOSITION, OR MODIFICATION OF THIS SOURCE CODE
# MAY RESULT IN CIVIL PENALTIES AND/OR CRIMINAL PENALTIES UNDER 18 U.S.C. § 641.

#!/bin/bash

rm -rf .vscode
rm bin/*.hpp
rm dump_model/*.csv
rm dump_model/*.keras
rm dump_model/*.h5
rm -rf codegen/__pycache__
rm -rf __pycache__
rm -rf dump_model/__pycache__
rm -rf training/__pycache__
rm *.csv